[project]
name = "empty-main"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "duckdb>=1.3.2",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.12.12",
]
